"""empty message

Revision ID: 96f5b6e57041
Revises: 1212cf48288c
Create Date: 2022-06-02 02:40:23.952425

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96f5b6e57041'
down_revision = '1212cf48288c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shows', 'artist_name')
    op.drop_column('shows', 'artist_image_link')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shows', sa.Column('artist_image_link', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.add_column('shows', sa.Column('artist_name', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
